// <auto-generated />
using DigitalMarket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalMarket.Migrations
{
    [DbContext(typeof(DigitalMarketDbContext))]
    [Migration("20220727175144__Init")]
    partial class _Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DigitalMarket.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Category = "Games",
                            Description = "Игра в жанре выживание, в которой вам предстоит исследовать огромный фэнтезийный мир, пропитанный скандинавской мифологией и культурой викингов.",
                            Price = 450m,
                            ProductName = "Valheim",
                            Seller = "Iron Gate"
                        },
                        new
                        {
                            ProductID = 2,
                            Category = "Games",
                            Description = "Кооперативная многопользовательская компьютерная игра в жанре приключенческого боевика с пиратской тематикой, разработанная компанией Rare и издаваемая Microsoft Studios.",
                            Price = 700m,
                            ProductName = "Sea of Thieves",
                            Seller = "Rare Studio"
                        },
                        new
                        {
                            ProductID = 3,
                            Category = "Games",
                            Description = "Мультиплатформенная компьютерная игра в жанре action-adventure с открытым миром",
                            Price = 700m,
                            ProductName = "Grand Theft Auto 5",
                            Seller = "Rockstar North"
                        },
                        new
                        {
                            ProductID = 4,
                            Category = "Games",
                            Description = "Компьютерная игра в жанре action-adventure, разработанная студией Rockstar North",
                            Price = 250m,
                            ProductName = "Grand Theft Auto: San Andreas",
                            Seller = "Rockstar North"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
